// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvaatxhcnyljiiiccqer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2YWF0eGhjbnlsamlpaWNjcWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjc3ODUsImV4cCI6MjA3Mzk0Mzc4NX0.i5bfSnVdHMk25c6Md5nFZE-XPDFQEszZ2ghOgE21lQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});